ask_ermakov/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from ask_ermakov.views import *
from django.views.generic import RedirectView

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'ask_ermakov.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       #    url(r'^', 'ask_ermakov.views.hello', name='hello'),
                       url(r'^$', index, name='index'),
                       url(r'^ask$', ask, name='ask'),
                       url(r'^signup$', register, name='register'),
                       url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
                       url(r'^login$', 'django.contrib.auth.views.login',
                           {'template_name': 'user/login.html', 'redirect_field_name': '/question'}),
                       url(r'^settings$', profile, name='settings'),
                       url(r'^accounts/profile/$', RedirectView.as_view(pattern_name='settings'), name='redirection'),
                       url(r'^question$', question),
                       )

ask_ermakov/models.py
from django.db import models
from django.contrib.auth.models import User
from ask_ermakov import settings

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User)
    rating = models.IntegerField(default=0)
    #avatar_url = models.CharField(max_length=60)
    avatar = models.ImageField(upload_to=settings.uploads, default='default.jpg')

    def __unicode__(self):
        return self.user.username


class Tag(models.Model):
    name = models.CharField(max_length=25)

    def __unicode__(self):
        return self.name

class Question(models.Model):
    author = models.ForeignKey(Profile)
    title = models.CharField(max_length=60)
    text = models.TextField()
    rating = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag)
    date_added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title


class Answer(models.Model):
    author = models.ForeignKey(Profile)
    question = models.ForeignKey(Question)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    is_right = models.BooleanField(default=False)

    def __unicode__(self):
        return self.text


class QuestionVote(models.Model):
    vote = models.IntegerField(default=0)
    user = models.ForeignKey(Profile)
    question = models.ForeignKey(Question)

    def __unicode__(self):
        return self.vote


class AnswerVote(models.Model):
    vote = models.IntegerField(default=0)
    user = models.ForeignKey(Profile)
    answer = models.ForeignKey(Answer)

    def __unicode__(self):
        return self.vote

templates/Layout.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Ask_Ermakov</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css"/>
    <link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css"/>
    <script src="jquery-2.1.3.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
</head>

<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="#">Ask_Ermakov</a>
            <ul class="nav">
                <li>
                    <a href="{% url 'index' %}">Вопросы</a>
                </li>
                <li class="divider-vertical"></li>
                <li><a href="{% url 'ask' %}">Задать вопрос</a></li>
                <li class="divider-vertical"></li>
                <li><a href="#">Пользователи</a></li>
                <li class="divider-vertical"></li>
            </ul>
            <ul class="nav pull-right">
                <li>
                    <form id="menu-search" class="form-search">
                        <div class="input-append">
                            <input type="text" class="span2 search-query">
                            <button type="submit" class="btn btn-inverse">
                                <i class="icon-search icon-white"></i>
                            </button>
                        </div>
                    </form>
                </li>
                <li class="divider-vertical"></li>
                <li class="divider-vertical"></li>
                <li>
                    {% if user.is_authenticated %}
                    <div class="btn-group">
                        <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">
                            <div id="avatar">
                                <img class="media-object" src="{{ user.profile.avatar }}">
                            </div>
                            {{user.username}}
                            <span id="caret-white" class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">
                                    <i class="icon-question-sign"></i>
                                    Мои вопросы
                                    <span class="label"></span>
                                </a>
                            </li>
                            <li>
                                <a  href="/settings">
                                    <i class="icon-wrench"></i>
                                    Настройки
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="/logout">
                                    <i class="icon-off"></i>
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </div>
                    {% else %}
                    <div class="btn-group">
                        <a class="btn btn-inverse" href="/login">
                            Войти
                        </a>
                    </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="main container">
    <div class="row-fluid">
        <div id="main_part" class="span8">
            {% block main %} {% endblock %}
        </div>
        <div class="span3 offset1">
            <div class="tags_authors">
            <h4>Популярные теги:<br>
                <span class="tag">
                    <a class="btn btn-mini" href="#">Что-то странное</a>
                </span>
                <span class="tag">
                    <a class="btn btn-mini" href="#">просто тег.</a>
                </span>
                 <span class="tag">
                    <a class="btn btn-mini" href="#">Никто</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">не</a>
                </span>
                 <span>
                    <a class="btn btn-mini" href="#">читает</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">теги.</a>
                </span>
            </h4>
                </div>
            <div class="tags_authors">
            <h4>Популярные авторы:<br>
                <span class="tag">
                    <a class="btn btn-mini" href="#">Михаил Булгаков</a>
                </span>
                <span class="tag">
                    <a class="btn btn-mini" href="#">Рэй Брэдбери</a>
                </span>
                 <span class="tag">
                    <a class="btn btn-mini" href="#">Федор Достоевский</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">Batman666</a>
                </span>
                 <span>
                    <a class="btn btn-mini" href="#">Стивен Кинг</a>
                </span>
            </h4>
                </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

templates/ask.html
{% extends "layout.html" %}

{% block main %}
<h2>Новый вопрос:</h2>
<br>	
<form method="POST" action="/ask">
	{% csrf_token %}
{% for field in form %}
	<div class="row-fluid">
		<div class="span2">
			<label style="width: 100%" for="{{ field.id_for_label }}">{{ field.label }}</label>
		</div>
		<div class="span5">
			{% if field.name == "title" %}
			<input style="resize: none; width: 100%;" autocomplete="off"
			id="{{ field.id_for_label }}" name="{{ field.name }}" type="text" 
			value="{{ field.value|default_if_none:"" }}"/>	
			{% elif field.name == "text" %}
			<textarea style="resize: none; width: 100%; height: 300px" 
			id="{{ field.id_for_label }}" name="{{ field.name }}" type="text" 
			value="{{ field.value|default_if_none:"" }}" ></textarea>	
			{% elif field.name == "tags" %}	
			<input style="resize: none; width: 100%;" name = "{{ field.name }}"type="text" 
			value="{{ field.value|default_if_none:"" }}"/>		
			{% endif %}
		</div>
	</div>
	{% if field.errors %}
		<div class="row-fluid">
			<div class="span2 offset2 alert alert-error"> 
				{{field.errors}}
			</div>
		</div>		
	{% endif %}

{% endfor %}
	<div class="row-fluid">
		<div class="span5 offset2">
				<input type="hidden" name="next" value="{{ next }}"/>
				<button type="submit" class="btn btn-info">Задать вопрос</button>
		</div>
	</div>
</form>

{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block main %}
    <h1>
        Популярные вопросы:
    </h1>
    <div id="questions">
    {% for Question in question_page %}
        <div class="question row-fluid">
            <div class="question_left span3">
                <img class="question_avatar" src="{{ Question.author.avatar }}"/>
                    Автор:
                <a>
                    {{ Question.author.user.username }}
                </a>
                <div class="btn-toolbar question_rate_outer">
                    <div class="btn-group question_rate_inner">
                        <a class="btn" href="#">-</a>
                        <a class="btn" href="#">{{ Question.rating }}</a>
                        <a class="btn" href="#">+</a>
                    </div>
                </div>
            </div>
            <div class="question_right span9">
                <h3><a href="/question?id={{Question.id}}">{{Question.title}}</a></h3>
                <p>
                    {{Question.text}}

                </p>
                <p class="question_tags">
                    Тэги: <br>
                    {% for tag in Question.tag_set.all %}
                        <span class="tag">
                            <a class="btn btn-mini" href="#">Что-то странное</a>
                        </span>
                    {% endfor %}
                </p>
                <a href="/question?id={{Question.id}}">Комментарии</a>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/profile.html
{% extends "layout.html" %}
{% block main %}
<h2>Profile of {{user.username}}</h2>	
<br>
<form  action="" method="post" enctype="multipart/form-data"> 
{% csrf_token %}
	{% for field in user_form %}
	<div class="row-fluid">
		<div class="span2">
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
		</div>
		<div class="span5">
			<input id="{{ field.id_for_label }}" name="{{ field.name }}" type="text"			
			value="{{ field.value|default_if_none:"" }}"/>			
		</div>
	</div>
	{% if field.errors %}
		<div class="row-fluid">
			<div class="span2 offset2 alert alert-error"> 
				{{field.errors}}
			</div>
		</div>		
	{% endif %}

	{% endfor %}
	<div class="row-fluid">
		<div class="span2">
			<p>Рейтинг</p>
		</div>
		<div class="span5">
				<label>{{user.profile.rating}}</label>				
		</div>
	</div>
	<div class="row-fluid">
		<div class="span2">
			<p>Загрузить аватар</p>
		</div>
		<div class="span5">
			<img class = "img" style = "margin-bottom: 15px" src="{{user.profile.avatar.url}}" heigth="100" width="100"/> 
			<div> {{profile_form.avatar}} </div>
		</div>
	</div>
	<br>
	<div class="row-fluid">
			<div class="span5 offset2">
					<input type="hidden" name="next" value="{{ next }}"/>
					<button type="submit" class="btn btn-info">Сохранить изменения</button>
			</div>
	</div>
</form>
{% endblock %}

templates/question.html
{% extends "layout.html" %}
{% block main %}
    <h2>Страница вопроса</h2>
    <div class="question row-fluid">
        <div class="question_left span3">
            <img class="question_avatar" src="{{ Question.author.user.profile.avatar }}"/>
            Автор:
            <a>
                {{ Question.author.user.username }}
            </a>

            <div class="btn-toolbar question_rate_outer">
                <div class="btn-group question_rate_inner">
                    <a class="btn" href="#">-</a>
                    <a class="btn" href="#">{{ Question.rating }}</a>
                    <a class="btn" href="#">+</a>
                </div>
            </div>
        </div>
        <div class="question_right span9">
            <h3><p>{{ Question.title }}</p></h3>
            <p>
                {{ Question.text }}

            </p>

            <p class="question_tags">
                Тэги: <br>
                <span class="tag">
                    <a class="btn btn-mini" href="#">Что-то странное</a>
                </span>
                <span class="tag">
                    <a class="btn btn-mini" href="#">просто тег.</a>
                </span>
                 <span class="tag">
                    <a class="btn btn-mini" href="#">Никто</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">не</a>
                </span>
                 <span>
                    <a class="btn btn-mini" href="#">читает</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">теги.</a>
                </span>
                     <span class="tag">
                    <a class="btn btn-mini" href="#">Тег</a>
                </span>
                <span class="tag">
                    <a class="btn btn-mini" href="#">.</a>
                </span>
                 <span class="tag">
                    <a class="btn btn-mini" href="#">111о</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">:)</a>
                </span>
                 <span>
                    <a class="btn btn-mini" href="#">18+</a>
                </span>
                <span>
                    <a class="btn btn-mini" href="#">теги.</a>
                </span>
            </p>
        </div>
    </div>
    <h2>Комментарии:</h2>
    {% for answer in Answers %}
        <div class="question row-fluid">
            <div class="question_left span3">
                <img class="answer_avatar" src="{{ answer.author.user.profile.avatar }}"/>
                Автор:
                <a>
                    {{ answer.author.user.username }}
                </a>

                <div class="btn-toolbar question_rate_outer">
                    <div class="btn-group question_rate_inner">
                        <a class="btn" href="#">-</a>
                        <a class="btn" href="#">{{ answer.rating }}</a>
                        <a class="btn" href="#">+</a>
                    </div>
                </div>
            </div>
            <div class="question_right span9">
                <p>
                    {{ answer.text}}
                </p>
            </div>
        </div>
    {% endfor %}
    {% if user.is_authenticated %}
        <form method="POST" action="">
            {% csrf_token %}
        <div class="row-fluid">
            <div class="span10" style="margin-top: 10px">
    	        <textarea style="resize: none; width: 100%;" name="{{ form.text.name }}" type="text"></textarea>
            </div>
            <div class="span1" style="margin-top: 10px">
                <button type="submit" style="margin-left:5px; height: 50px" class="btn btn-primary">Ответить</button>
            </div>
            {% if form.text.errors %}
                <div class="alert alert-error">
                    {{ form.text.errors }}
                </div>
            {% endif %}
            <br>
            </div>
        </form>
    {% endif %}
{% endblock %}